#!/bin/bash

PURPLE='\033[0;35m'
RED='\033[0;31m'
NC='\033[0m'

pattern='^(\[code]:|\[test]:|\[tools]:)'
msg="\nAborting commmit - message doesn't match pattern!\nPlease use: [code]: or [test]: or [tools]: instead\n"

echo -e ""$(date +"%T":"%N")" ${PURPLE}[### ]${NC} Commit-msg Started"

if ! grep -iqE "$pattern" "$1"; then
    echo -e "$msg"
    echo -e ""$(date +"%T":"%N")" ${RED}[### ]${NC} Commit-msg Failed"
    exit 1;
else
    echo -e ""$(date +"%T":"%N")" ${PURPLE}[####]${NC} Commit-msg Finished"
fi
