#!/bin/bash

PURPLE='\033[0;35m'
RED='\033[0;31m'
NC='\033[0m'

echo -e ""$(date +"%T":"%N")" ${PURPLE}[#   ]${NC} Pre-commit Started"

if [[ $(find . -name "*.sh" -exec /usr/bin/shellcheck {} \;) ]]; then
    echo "Please fix: $(find . -name "*.sh" -exec /usr/bin/shellcheck {} \;)"
    echo -e ""$(date +"%T":"%N")" ${RED}[#   ]${NC} Pre-commit Failed"
    exit 1
else
    echo "-- Shellcheck passed"
fi

(./utils/buildAndCompile.sh\
    && echo -e ""$(date +"%T":"%N")" ${PURPLE}[##  ]${NC} Pre-commit Finished")\
        || (echo -e ""$(date +"%T":"%N")" ${RED}[#   ]${NC} Pre-commit Failed"; exit 1)
